name: palominos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  firebase_storage: ^11.6.11
  firebase_ui_auth: ^1.13.1
  flutter:
    sdk: flutter
  go_router: ^13.2.1
  google_fonts: ^6.2.1
  hexcolor: ^3.0.1
  image_picker: ^1.0.7
  provider: ^6.1.2 



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/