// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB17KF_U1D0k7UDCXoksoMJHlTq5FFb28',
    appId: '1:1063379790240:web:004d76d85412470ba85cc5',
    messagingSenderId: '1063379790240',
    projectId: 'basededatospalominos',
    authDomain: 'basededatospalominos.firebaseapp.com',
    storageBucket: 'basededatospalominos.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQVhxNjEUaDYBL_yT7W6ysYVHvkSl_XeM',
    appId: '1:1063379790240:android:4058f38c6df85647a85cc5',
    messagingSenderId: '1063379790240',
    projectId: 'basededatospalominos',
    storageBucket: 'basededatospalominos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV937q8WcIa_RgMNI2iNySs6JvEuO-2U0',
    appId: '1:1063379790240:ios:39ea866c0602fc6ca85cc5',
    messagingSenderId: '1063379790240',
    projectId: 'basededatospalominos',
    storageBucket: 'basededatospalominos.appspot.com',
    iosBundleId: 'com.example.palominos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV937q8WcIa_RgMNI2iNySs6JvEuO-2U0',
    appId: '1:1063379790240:ios:c28b64fc540ea45ba85cc5',
    messagingSenderId: '1063379790240',
    projectId: 'basededatospalominos',
    storageBucket: 'basededatospalominos.appspot.com',
    iosBundleId: 'com.example.palominos.RunnerTests',
  );
}
